### PR TITLE
Feat/84593 open school application form in new tab

### PR DESCRIPTION
**Pull request by sureshbabukuruva**

### CODE REVIEW

**Review by CathLass — COMMENTED** [review]
There may have been a misunderstanding as to the requirements for this feature. I suggest you catch up with Michael Palmer and Sharondeep to demo your branch to them and check it meets requirements before we do a code review.

**Review by MartinWheelerMT — CHANGES_REQUESTED** [review]
The code itself looks okay.  I'm not that familiar with a2b-internal, but this looks like it is recreating some of the code from the original page (not the one in the new tab).  Is there no where we can share some of this code rather than duplicating it? I think the way this is working, if there was a change to the form we would have to change it in two places?

**Comment by sureshbabukuruva** [comment]
> The code itself looks okay. I'm not that familiar with a2b-internal, but this looks like it is recreating some of the code from the original page (not the one in the new tab). Is there no where we can share some of this code rather than duplicating it? I think the way this is working, if there was a change to the form we would have to change it in two places?

**Comment by sureshbabukuruva** [comment]
In new screen , most of the code i have used , in case if i change the original code need to do more regression as existing functionality will change, in this case please suggest if you still need me to change

**Pull request closed without merging**
